language: ruby
rvm:
  - 2.3.0
sudo: required
script:
  - "chmod +x script/build.sh"
  - "./script/build.sh"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_deploy:
  - "nvm install v7.10.0"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"