collections:
    photo_gallery:

# Custom Excludes
exclude: ["Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "firebase.json", "vendor/", "node_modules/", "src/", "script/", "package-lock.json", "README.md"]
